[build]
builder = "NIXPACKS"
nixpacksConfigPath = ""

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python312", "ffmpeg-full", "ghostscript", "poppler_utils"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
